### ISSUE TITLE
Create screen to do a task in real life

### ISSUE THREAD

**Issue by ErwinPrograms** [MyOCGrunkleStanLee/Gladitorial_Tasks#9]
Bare Minimum: 

- Text on screen that tells you to do a task in real life
- An event (button or timer) that does one of two things
    - Cycle back to combat screen
    - End cycle and go to conclusion (could just quit game)

**Comment by salzig1** [comment]
<img width="1316" alt="Bildschirmfoto 2024-05-17 um 17 13 52" src="https://github.com/MyOCGrunkleStanLee/Gladitorial_Tasks/assets/73057723/d2b35a0f-7e98-464b-bff8-6ab1bd183d9f">

The do_it_irl screen now consists of:
- a timer
- a start timer button
- a finish button
- an image with instruction text on it

So basically we need sprites for the two buttons and for every instruction (we can probably reuse the instruction sprites from the break it down screen)
